# Form implementation generated from reading ui file 'ELFB/palettes/AddEgDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEg(object):
    def setupUi(self, AddEg):
        AddEg.setObjectName("AddEg")
        AddEg.resize(227, 149)
        AddEg.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=AddEg)
        self.label.setMinimumSize(QtCore.QSize(0, 16))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.IDRef = QtWidgets.QLineEdit(parent=AddEg)
        self.IDRef.setMinimumSize(QtCore.QSize(0, 24))
        self.IDRef.setMaximumSize(QtCore.QSize(16777215, 24))
        self.IDRef.setObjectName("IDRef")
        self.verticalLayout.addWidget(self.IDRef)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(parent=AddEg)
        font = QtGui.QFont()
        font.setItalic(True)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddEg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddEg)
        QtCore.QMetaObject.connectSlotsByName(AddEg)

    def retranslateUi(self, AddEg):
        _translate = QtCore.QCoreApplication.translate
        AddEg.setWindowTitle(_translate("AddEg", "Add example"))
        self.label.setText(_translate("AddEg", "Enter IDREF"))
        self.IDRef.setToolTip(_translate("AddEg", "Add the ID number of the example to add.\n"
"This can be copied-and-pasted from the\n"
"top left corner of the example viewed in the\n"
"Examples tab."))
        self.checkBox.setToolTip(_translate("AddEg", "check to add the example currently \n"
"visible in the Examples tab"))
        self.checkBox.setText(_translate("AddEg", "Add current example"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEg = QtWidgets.QDialog()
    ui = Ui_AddEg()
    ui.setupUi(AddEg)
    AddEg.show()
    sys.exit(app.exec())
