# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/David/Library/Mobile Documents/com~apple~CloudDocs/Current/ELFB/eFieldBook_Qt5/ELFB/palettes/EgSearchDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchExamples(object):
    def setupUi(self, SearchExamples):
        SearchExamples.setObjectName("SearchExamples")
        SearchExamples.resize(517, 368)
        SearchExamples.setStyleSheet("QPushButton {\n"
"    max-height: 19px;\n"
"    min-height: 19px;\n"
"    max-width: 60px;\n"
"    min-width: 60px;\n"
"    background: #6698FF;\n"
"    color: white;    \n"
"    border: 0px solid black;\n"
"    border-radius: 4px;\n"
"        padding: 0 0 0 0;\n"
"        margin: 0 0 0 0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #1E90FF;\n"
"    border: 2px outset #E6E6FA;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #E6E6FA;\n"
"    border: 0px outset #E6E6FA;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(SearchExamples)
        self.buttonBox.setGeometry(QtCore.QRect(345, 325, 142, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(SearchExamples)
        self.groupBox.setGeometry(QtCore.QRect(349, 0, 148, 107))
        self.groupBox.setObjectName("groupBox")
        self.Source = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Source.setGeometry(QtCore.QRect(8, 39, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Source.setFont(font)
        self.Source.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Source.setObjectName("Source")
        self.Researcher = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Researcher.setGeometry(QtCore.QRect(80, 39, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Researcher.setFont(font)
        self.Researcher.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Researcher.setObjectName("Researcher")
        self.Date = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Date.setGeometry(QtCore.QRect(8, 78, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Date.setFont(font)
        self.Date.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Date.setObjectName("Date")
        self.Updated = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Updated.setGeometry(QtCore.QRect(80, 78, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Updated.setFont(font)
        self.Updated.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Updated.setObjectName("Updated")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(8, 22, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 22, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(8, 61, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(80, 61, 44, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(SearchExamples)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 280, 150, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Comments = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.Comments.setGeometry(QtCore.QRect(8, 22, 134, 42))
        self.Comments.setObjectName("Comments")
        self.groupBox_3 = QtWidgets.QGroupBox(SearchExamples)
        self.groupBox_3.setGeometry(QtCore.QRect(182, 280, 150, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Keywords = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.Keywords.setGeometry(QtCore.QRect(8, 22, 134, 42))
        self.Keywords.setObjectName("Keywords")
        self.groupBox_4 = QtWidgets.QGroupBox(SearchExamples)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 0, 312, 279))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1, 15, 311, 262))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(8, 0, 8, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.Line = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.Line.setMinimumSize(QtCore.QSize(295, 25))
        self.Line.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Line.setFont(font)
        self.Line.setObjectName("Line")
        self.verticalLayout.addWidget(self.Line)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.Morph = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.Morph.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Morph.setFont(font)
        self.Morph.setObjectName("Morph")
        self.verticalLayout.addWidget(self.Morph)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.ILEG = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.ILEG.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ILEG.setFont(font)
        self.ILEG.setObjectName("ILEG")
        self.verticalLayout.addWidget(self.ILEG)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.L1Gloss = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.L1Gloss.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.L1Gloss.setFont(font)
        self.L1Gloss.setObjectName("L1Gloss")
        self.verticalLayout.addWidget(self.L1Gloss)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.L2Gloss = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.L2Gloss.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.L2Gloss.setFont(font)
        self.L2Gloss.setObjectName("L2Gloss")
        self.verticalLayout.addWidget(self.L2Gloss)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(SearchExamples)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(371, 114, 130, 155))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.caseBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.caseBtn.setFont(font)
        self.caseBtn.setChecked(True)
        self.caseBtn.setObjectName("caseBtn")
        self.verticalLayout_2.addWidget(self.caseBtn)
        self.accentBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.accentBtn.setFont(font)
        self.accentBtn.setObjectName("accentBtn")
        self.verticalLayout_2.addWidget(self.accentBtn)
        self.diacritBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.diacritBtn.setFont(font)
        self.diacritBtn.setObjectName("diacritBtn")
        self.verticalLayout_2.addWidget(self.diacritBtn)
        self.wholeWordBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.wholeWordBtn.setFont(font)
        self.wholeWordBtn.setObjectName("wholeWordBtn")
        self.verticalLayout_2.addWidget(self.wholeWordBtn)
        self.recOnlyBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.recOnlyBtn.setFont(font)
        self.recOnlyBtn.setObjectName("recOnlyBtn")
        self.verticalLayout_2.addWidget(self.recOnlyBtn)
        self.appendBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.appendBtn.setFont(font)
        self.appendBtn.setObjectName("appendBtn")
        self.verticalLayout_2.addWidget(self.appendBtn)
        self.setLangBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.setLangBtn.setFont(font)
        self.setLangBtn.setObjectName("setLangBtn")
        self.verticalLayout_2.addWidget(self.setLangBtn)
        self.egSearchHelpBtn = QtWidgets.QPushButton(SearchExamples)
        self.egSearchHelpBtn.setGeometry(QtCore.QRect(423, 293, 60, 19))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.egSearchHelpBtn.setFont(font)
        self.egSearchHelpBtn.setObjectName("egSearchHelpBtn")
        self.clearBtn = QtWidgets.QPushButton(SearchExamples)
        self.clearBtn.setGeometry(QtCore.QRect(351, 293, 60, 19))
        self.clearBtn.setObjectName("clearBtn")

        self.retranslateUi(SearchExamples)
        self.buttonBox.accepted.connect(SearchExamples.accept)
        self.buttonBox.rejected.connect(SearchExamples.reject)
        QtCore.QMetaObject.connectSlotsByName(SearchExamples)
        SearchExamples.setTabOrder(self.Line, self.Morph)
        SearchExamples.setTabOrder(self.Morph, self.ILEG)
        SearchExamples.setTabOrder(self.ILEG, self.L1Gloss)
        SearchExamples.setTabOrder(self.L1Gloss, self.L2Gloss)
        SearchExamples.setTabOrder(self.L2Gloss, self.Comments)
        SearchExamples.setTabOrder(self.Comments, self.Keywords)
        SearchExamples.setTabOrder(self.Keywords, self.Source)
        SearchExamples.setTabOrder(self.Source, self.Researcher)
        SearchExamples.setTabOrder(self.Researcher, self.Date)
        SearchExamples.setTabOrder(self.Date, self.Updated)
        SearchExamples.setTabOrder(self.Updated, self.buttonBox)
        SearchExamples.setTabOrder(self.buttonBox, self.caseBtn)
        SearchExamples.setTabOrder(self.caseBtn, self.accentBtn)
        SearchExamples.setTabOrder(self.accentBtn, self.diacritBtn)
        SearchExamples.setTabOrder(self.diacritBtn, self.appendBtn)

    def retranslateUi(self, SearchExamples):
        _translate = QtCore.QCoreApplication.translate
        SearchExamples.setWindowTitle(_translate("SearchExamples", "Dialog"))
        SearchExamples.setToolTip(_translate("SearchExamples", "select search help (?) button for instructions"))
        self.groupBox.setTitle(_translate("SearchExamples", "Metadata"))
        self.label.setText(_translate("SearchExamples", "Source"))
        self.label_2.setText(_translate("SearchExamples", "Researcher"))
        self.label_3.setText(_translate("SearchExamples", "Date"))
        self.label_4.setText(_translate("SearchExamples", "Updated"))
        self.groupBox_2.setTitle(_translate("SearchExamples", "Comments"))
        self.groupBox_3.setTitle(_translate("SearchExamples", "Keywords"))
        self.groupBox_4.setTitle(_translate("SearchExamples", "Example"))
        self.label_5.setText(_translate("SearchExamples", "Line"))
        self.label_6.setText(_translate("SearchExamples", "Morph"))
        self.label_7.setText(_translate("SearchExamples", "ILEG"))
        self.label_8.setText(_translate("SearchExamples", "Primary language gloss"))
        self.label_9.setText(_translate("SearchExamples", "Secondary language gloss"))
        self.caseBtn.setToolTip(_translate("SearchExamples", "Perform case-insensitive searches"))
        self.caseBtn.setText(_translate("SearchExamples", "Ignore case"))
        self.accentBtn.setToolTip(_translate("SearchExamples", "Perform searches that ignore lexical accent.\n"
"Search term must contain no accented characters."))
        self.accentBtn.setText(_translate("SearchExamples", "Ignore accents"))
        self.diacritBtn.setToolTip(_translate("SearchExamples", "Perform searches that ignore diacritics. \n"
"Search term must contain no diacritics."))
        self.diacritBtn.setText(_translate("SearchExamples", "Ignore diacrits"))
        self.wholeWordBtn.setText(_translate("SearchExamples", "Whole word"))
        self.recOnlyBtn.setToolTip(_translate("SearchExamples", "Find only examples with recordings"))
        self.recOnlyBtn.setText(_translate("SearchExamples", "Recorded only"))
        self.appendBtn.setToolTip(_translate("SearchExamples", "Search results will not overwrite the results\n"
"of previous searches on \"Search\" card."))
        self.appendBtn.setText(_translate("SearchExamples", "Append results"))
        self.setLangBtn.setText(_translate("SearchExamples", "Second language"))
        self.egSearchHelpBtn.setToolTip(_translate("SearchExamples", "search help"))
        self.egSearchHelpBtn.setText(_translate("SearchExamples", "Help"))
        self.clearBtn.setText(_translate("SearchExamples", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchExamples = QtWidgets.QDialog()
    ui = Ui_SearchExamples()
    ui.setupUi(SearchExamples)
    SearchExamples.show()
    sys.exit(app.exec_())

