# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/David/Google Drive/Current/ELFB/eFieldBook_Qt5/ELFB/palettes/LexSearchForm.ui'
#
# Created by: PyQt6 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LexSearchForm(object):
    def setupUi(self, LexSearchForm):
        LexSearchForm.setObjectName("LexSearchForm")
        LexSearchForm.resize(1126, 686)
        LexSearchForm.setAutoFillBackground(True)
        LexSearchForm.setStyleSheet("QFrame {\n"
                                    "     border: 0px solid black;\n"
                                    "     border-radius: 8px;\n"
                                    "     padding: 0px;\n"
                                    "     background-color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit {\n"
                                    "     border: 0px solid black;\n"
                                    "     border-radius: 8px;\n"
                                    "     padding: 0px;\n"
                                    "     background-color: rgb(255, 255, 255);\n"
                                    "}")
        self.lSearchHeader = QtWidgets.QGroupBox(LexSearchForm)
        self.lSearchHeader.setGeometry(QtCore.QRect(7, -2, 965, 138))
        self.lSearchHeader.setStyleSheet("QLineEdit {\n"
                                         "    padding-left: 3px;\n"
                                         "}")
        self.lSearchHeader.setObjectName("lSearchHeader")
        self.lSearchOrth = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchOrth.setGeometry(QtCore.QRect(74, 24, 473, 39))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lSearchOrth.setFont(font)
        self.lSearchOrth.setStyleSheet("QLineEdit {\n"
                                       "     border: 0px solid black;\n"
                                       "     border-radius: 0px;\n"
                                       "     padding: 0px;\n"
                                       "}")
        self.lSearchOrth.setObjectName("lSearchOrth")
        self.lSearchIPA = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchIPA.setGeometry(QtCore.QRect(74, 68, 473, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lSearchIPA.setFont(font)
        self.lSearchIPA.setStyleSheet("QLineEdit {\n"
                                      "     border: 0px solid black;\n"
                                      "     border-radius: 0px;\n"
                                      "     padding: 0px;\n"
                                      "}")
        self.lSearchIPA.setObjectName("lSearchIPA")
        self.notations = QtWidgets.QGroupBox(self.lSearchHeader)
        self.notations.setGeometry(QtCore.QRect(703, 22, 194, 112))
        sizePolicy = QtWidgets.QSizePolicy()
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notations.sizePolicy().hasHeightForWidth())
        self.notations.setSizePolicy(sizePolicy)
        self.notations.setMinimumSize(QtCore.QSize(194, 112))
        self.notations.setMaximumSize(QtCore.QSize(194, 112))
        self.notations.setTitle("")
        self.notations.setObjectName("notations")
        self.lCatSearch = QtWidgets.QLineEdit(self.notations)
        self.lCatSearch.setGeometry(QtCore.QRect(7, 7, 50, 28))
        self.lCatSearch.setMinimumSize(QtCore.QSize(50, 28))
        self.lCatSearch.setMaximumSize(QtCore.QSize(50, 28))
        self.lCatSearch.setObjectName("lCatSearch")
        self.lGrmSearch = QtWidgets.QLineEdit(self.notations)
        self.lGrmSearch.setGeometry(QtCore.QRect(64, 7, 120, 28))
        self.lGrmSearch.setMinimumSize(QtCore.QSize(120, 28))
        self.lGrmSearch.setMaximumSize(QtCore.QSize(120, 28))
        self.lGrmSearch.setObjectName("lGrmSearch")
        self.lC2Search = QtWidgets.QLineEdit(self.notations)
        self.lC2Search.setGeometry(QtCore.QRect(7, 42, 178, 28))
        self.lC2Search.setMinimumSize(QtCore.QSize(178, 28))
        self.lC2Search.setMaximumSize(QtCore.QSize(178, 28))
        self.lC2Search.setObjectName("lC2Search")
        self.lCfSearch = QtWidgets.QLineEdit(self.notations)
        self.lCfSearch.setGeometry(QtCore.QRect(7, 77, 178, 28))
        self.lCfSearch.setMinimumSize(QtCore.QSize(178, 28))
        self.lCfSearch.setMaximumSize(QtCore.QSize(178, 28))
        self.lCfSearch.setObjectName("lCfSearch")
        self.lSearchLit = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchLit.setGeometry(QtCore.QRect(9, 104, 633, 26))
        self.lSearchLit.setObjectName("lSearchLit")
        self.lSearchPOS = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchPOS.setGeometry(QtCore.QRect(9, 28, 57, 30))
        self.lSearchPOS.setObjectName("lSearchPOS")
        self.lSearchRegister = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchRegister.setGeometry(QtCore.QRect(9, 70, 57, 26))
        self.lSearchRegister.setObjectName("lSearchRegister")
        self.lSearchBrrw = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchBrrw.setGeometry(QtCore.QRect(554, 69, 140, 28))
        self.lSearchBrrw.setObjectName("lSearchBrrw")
        self.lSearchDialectName = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lSearchDialectName.setGeometry(QtCore.QRect(554, 30, 45, 28))
        self.lSearchDialectName.setObjectName("lSearchDialectName")
        self.lDialectSearch = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lDialectSearch.setGeometry(QtCore.QRect(606, 30, 87, 28))
        self.lDialectSearch.setObjectName("lDialectSearch")
        self.lGrmDialectSearch = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lGrmDialectSearch.setGeometry(QtCore.QRect(894, 29, 50, 28))
        self.lGrmDialectSearch.setMinimumSize(QtCore.QSize(50, 28))
        self.lGrmDialectSearch.setMaximumSize(QtCore.QSize(50, 28))
        self.lGrmDialectSearch.setObjectName("lGrmDialectSearch")
        self.lC2DialectSearch = QtWidgets.QLineEdit(self.lSearchHeader)
        self.lC2DialectSearch.setGeometry(QtCore.QRect(894, 64, 50, 28))
        self.lC2DialectSearch.setMinimumSize(QtCore.QSize(50, 28))
        self.lC2DialectSearch.setMaximumSize(QtCore.QSize(50, 28))
        self.lC2DialectSearch.setObjectName("lC2DialectSearch")
        self.lMetadataBox = QtWidgets.QGroupBox(LexSearchForm)
        self.lMetadataBox.setGeometry(QtCore.QRect(976, -2, 148, 138))
        sizePolicy = QtWidgets.QSizePolicy()
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lMetadataBox.sizePolicy().hasHeightForWidth())
        self.lMetadataBox.setSizePolicy(sizePolicy)
        self.lMetadataBox.setStyleSheet("QLineEdit {\n"
                                        "    font-size: 9;\n"
                                        "    border-radius: 0pts;\n"
                                        "    max-height: 16px;\n"
                                        "    min-width: 45px;\n"
                                        "    min-height: 16px;\n"
                                        "    padding: 1px;\n"
                                        "}\n"
                                        "\n"
                                        "QLabel {\n"
                                        "    background: transparent;\n"
                                        "}")
        self.lMetadataBox.setObjectName("lMetadataBox")
        self.lLabelSource = QtWidgets.QLabel(self.lMetadataBox)
        self.lLabelSource.setGeometry(QtCore.QRect(8, 22, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lLabelSource.setFont(font)
        self.lLabelSource.setAutoFillBackground(False)
        self.lLabelSource.setObjectName("lLabelSource")
        self.lLabelDate = QtWidgets.QLabel(self.lMetadataBox)
        self.lLabelDate.setGeometry(QtCore.QRect(8, 59, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lLabelDate.setFont(font)
        self.lLabelDate.setAutoFillBackground(False)
        self.lLabelDate.setObjectName("lLabelDate")
        self.lLabelResearcher = QtWidgets.QLabel(self.lMetadataBox)
        self.lLabelResearcher.setGeometry(QtCore.QRect(80, 22, 52, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lLabelResearcher.setFont(font)
        self.lLabelResearcher.setAutoFillBackground(False)
        self.lLabelResearcher.setObjectName("lLabelResearcher")
        self.lLabelConfirmed = QtWidgets.QLabel(self.lMetadataBox)
        self.lLabelConfirmed.setGeometry(QtCore.QRect(8, 96, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lLabelConfirmed.setFont(font)
        self.lLabelConfirmed.setAutoFillBackground(False)
        self.lLabelConfirmed.setLineWidth(0)
        self.lLabelConfirmed.setObjectName("lLabelConfirmed")
        self.lLabelUpdated = QtWidgets.QLabel(self.lMetadataBox)
        self.lLabelUpdated.setGeometry(QtCore.QRect(80, 59, 37, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lLabelUpdated.setFont(font)
        self.lLabelUpdated.setAutoFillBackground(False)
        self.lLabelUpdated.setObjectName("lLabelUpdated")
        self.lSearchSource = QtWidgets.QLineEdit(self.lMetadataBox)
        self.lSearchSource.setGeometry(QtCore.QRect(8, 39, 60, 18))
        self.lSearchSource.setObjectName("lSearchSource")
        self.lSearchResearcher = QtWidgets.QLineEdit(self.lMetadataBox)
        self.lSearchResearcher.setGeometry(QtCore.QRect(80, 39, 60, 18))
        self.lSearchResearcher.setObjectName("lSearchResearcher")
        self.lSearchDate = QtWidgets.QLineEdit(self.lMetadataBox)
        self.lSearchDate.setGeometry(QtCore.QRect(8, 76, 60, 18))
        self.lSearchDate.setObjectName("lSearchDate")
        self.lSearchUpdate = QtWidgets.QLineEdit(self.lMetadataBox)
        self.lSearchUpdate.setGeometry(QtCore.QRect(80, 76, 60, 18))
        self.lSearchUpdate.setObjectName("lSearchUpdate")
        self.lSearchConfirmed = QtWidgets.QLineEdit(self.lMetadataBox)
        self.lSearchConfirmed.setGeometry(QtCore.QRect(8, 113, 132, 18))
        self.lSearchConfirmed.setObjectName("lSearchConfirmed")
        self.lDefBox = QtWidgets.QGroupBox(LexSearchForm)
        self.lDefBox.setGeometry(QtCore.QRect(166, 136, 732, 338))
        self.lDefBox.setStyleSheet("")
        self.lDefBox.setObjectName("lDefBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lDefBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lL1Box = QtWidgets.QGroupBox(self.lDefBox)
        self.lL1Box.setAutoFillBackground(False)
        self.lL1Box.setFlat(False)
        self.lL1Box.setObjectName("lL1Box")
        self.lL1Search = QtWidgets.QLineEdit(self.lL1Box)
        self.lL1Search.setGeometry(QtCore.QRect(7, 26, 689, 116))
        self.lL1Search.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lL1Search.setObjectName("lL1Search")
        self.verticalLayout.addWidget(self.lL1Box)
        self.lL2Box = QtWidgets.QGroupBox(self.lDefBox)
        self.lL2Box.setObjectName("lL2Box")
        self.lL2Search = QtWidgets.QLineEdit(self.lL2Box)
        self.lL2Search.setGeometry(QtCore.QRect(7, 26, 689, 116))
        self.lL2Search.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lL2Search.setObjectName("lL2Search")
        self.verticalLayout.addWidget(self.lL2Box)
        self.lIndexBox = QtWidgets.QGroupBox(LexSearchForm)
        self.lIndexBox.setGeometry(QtCore.QRect(166, 472, 731, 112))
        self.lIndexBox.setStyleSheet("")
        self.lIndexBox.setObjectName("lIndexBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.lIndexBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lKeywordsBox = QtWidgets.QGroupBox(self.lIndexBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lKeywordsBox.sizePolicy().hasHeightForWidth())
        self.lKeywordsBox.setSizePolicy(sizePolicy)
        self.lKeywordsBox.setMinimumSize(QtCore.QSize(220, 0))
        self.lKeywordsBox.setAutoFillBackground(False)
        self.lKeywordsBox.setStyleSheet("QGroupBox.title {\n"
                                        "    background-color: transparent;\n"
                                        "}")
        self.lKeywordsBox.setObjectName("lKeywordsBox")
        self.lSearchKeywordIndex = QtWidgets.QLineEdit(self.lKeywordsBox)
        self.lSearchKeywordIndex.setGeometry(QtCore.QRect(7, 25, 201, 43))
        self.lSearchKeywordIndex.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lSearchKeywordIndex.setObjectName("lSearchKeywordIndex")
        self.horizontalLayout_3.addWidget(self.lKeywordsBox)
        self.lPrimaryIndexBox = QtWidgets.QGroupBox(self.lIndexBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lPrimaryIndexBox.sizePolicy().hasHeightForWidth())
        self.lPrimaryIndexBox.setSizePolicy(sizePolicy)
        self.lPrimaryIndexBox.setMinimumSize(QtCore.QSize(220, 0))
        self.lPrimaryIndexBox.setObjectName("lPrimaryIndexBox")
        self.lSearchPrimaryIndex = QtWidgets.QLineEdit(self.lPrimaryIndexBox)
        self.lSearchPrimaryIndex.setGeometry(QtCore.QRect(7, 25, 207, 43))
        self.lSearchPrimaryIndex.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lSearchPrimaryIndex.setObjectName("lSearchPrimaryIndex")
        self.horizontalLayout_3.addWidget(self.lPrimaryIndexBox)
        self.lSecondaryIndexBox = QtWidgets.QGroupBox(self.lIndexBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lSecondaryIndexBox.sizePolicy().hasHeightForWidth())
        self.lSecondaryIndexBox.setSizePolicy(sizePolicy)
        self.lSecondaryIndexBox.setMinimumSize(QtCore.QSize(220, 0))
        self.lSecondaryIndexBox.setObjectName("lSecondaryIndexBox")
        self.lSearchSecondaryIndex = QtWidgets.QLineEdit(self.lSecondaryIndexBox)
        self.lSearchSecondaryIndex.setGeometry(QtCore.QRect(7, 25, 207, 43))
        self.lSearchSecondaryIndex.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lSearchSecondaryIndex.setObjectName("lSearchSecondaryIndex")
        self.horizontalLayout_3.addWidget(self.lSecondaryIndexBox)
        self.instructionBox = QtWidgets.QGroupBox(LexSearchForm)
        self.instructionBox.setGeometry(QtCore.QRect(912, 136, 210, 448))
        self.instructionBox.setObjectName("instructionBox")
        self.instruction = QtWidgets.QTextEdit(self.instructionBox)
        self.instruction.setGeometry(QtCore.QRect(11, 27, 190, 410))
        self.instruction.setReadOnly(True)
        self.instruction.setObjectName("instruction")
        self.sDoneBtn = QtWidgets.QCheckBox(LexSearchForm)
        self.sDoneBtn.setGeometry(QtCore.QRect(920, 117, 54, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.sDoneBtn.setFont(font)
        self.sDoneBtn.setTristate(True)
        self.sDoneBtn.setObjectName("sDoneBtn")
        self.lSearchControlBar = QtWidgets.QFrame(LexSearchForm)
        self.lSearchControlBar.setGeometry(QtCore.QRect(166, 596, 258, 54))
        self.lSearchControlBar.setMinimumSize(QtCore.QSize(258, 54))
        self.lSearchControlBar.setMaximumSize(QtCore.QSize(258, 54))
        self.lSearchControlBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.lSearchControlBar.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lSearchControlBar.setObjectName("lSearchControlBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.lSearchControlBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doSearch = QtWidgets.QPushButton(self.lSearchControlBar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doSearch.setFont(font)
        self.doSearch.setObjectName("doSearch")
        self.horizontalLayout.addWidget(self.doSearch)
        self.lCancelSearch = QtWidgets.QPushButton(self.lSearchControlBar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lCancelSearch.setFont(font)
        self.lCancelSearch.setObjectName("lCancelSearch")
        self.horizontalLayout.addWidget(self.lCancelSearch)
        self.clearForm = QtWidgets.QPushButton(self.lSearchControlBar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.clearForm.setFont(font)
        self.clearForm.setObjectName("clearForm")
        self.horizontalLayout.addWidget(self.clearForm)
        self.doSearch.raise_()
        self.clearForm.raise_()
        self.lCancelSearch.raise_()
        self.searchParam = QtWidgets.QGroupBox(LexSearchForm)
        self.searchParam.setGeometry(QtCore.QRect(8, 136, 147, 213))
        self.searchParam.setStyleSheet("QCheckBox {font-size: 10pts; font-style: italic;}")
        self.searchParam.setObjectName("searchParam")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.searchParam)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 19, 131, 193))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.caseBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.caseBtn.setChecked(True)
        self.caseBtn.setObjectName("caseBtn")
        self.verticalLayout_2.addWidget(self.caseBtn)
        self.accentBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.accentBtn.setChecked(True)
        self.accentBtn.setObjectName("accentBtn")
        self.verticalLayout_2.addWidget(self.accentBtn)
        self.diacritBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.diacritBtn.setChecked(True)
        self.diacritBtn.setObjectName("diacritBtn")
        self.verticalLayout_2.addWidget(self.diacritBtn)
        self.appendBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.appendBtn.setObjectName("appendBtn")
        self.verticalLayout_2.addWidget(self.appendBtn)
        self.wholeWordBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.wholeWordBtn.setObjectName("wholeWordBtn")
        self.verticalLayout_2.addWidget(self.wholeWordBtn)
        self.setLangBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.setLangBtn.setObjectName("setLangBtn")
        self.verticalLayout_2.addWidget(self.setLangBtn)
        self.lSearchNotes = QtWidgets.QLineEdit(LexSearchForm)
        self.lSearchNotes.setGeometry(QtCore.QRect(495, 596, 403, 54))
        self.lSearchNotes.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lSearchNotes.setObjectName("lSearchNotes")

        self.retranslateUi(LexSearchForm)
        QtCore.QMetaObject.connectSlotsByName(LexSearchForm)

    def retranslateUi(self, LexSearchForm):
        _translate = QtCore.QCoreApplication.translate
        LexSearchForm.setWindowTitle(_translate("LexSearchForm", "Form"))
        LexSearchForm.setToolTip(_translate("LexSearchForm", "Perform searches that ignore diacritics.\n"
                                                             "Search term must contain no diacritics."))
        self.lSearchHeader.setTitle(_translate("LexSearchForm", "Lexicographic info"))
        self.lSearchOrth.setToolTip(_translate("LexSearchForm", "search orthographic form"))
        self.lSearchIPA.setToolTip(_translate("LexSearchForm", "search phonemic form"))
        self.lCatSearch.setToolTip(_translate("LexSearchForm", "search grammatical labels (e.g., \"pl.\")"))
        self.lGrmSearch.setToolTip(_translate("LexSearchForm", "search for grammatical forms"))
        self.lC2Search.setToolTip(_translate("LexSearchForm", "search for comparisons"))
        self.lCfSearch.setToolTip(_translate("LexSearchForm", "search cross-references"))
        self.lSearchLit.setToolTip(_translate("LexSearchForm", "search literal glosses"))
        self.lSearchPOS.setToolTip(_translate("LexSearchForm", "search by part of speech"))
        self.lSearchRegister.setToolTip(_translate("LexSearchForm", "search by register"))
        self.lSearchBrrw.setToolTip(_translate("LexSearchForm", "search borrowings"))
        self.lSearchDialectName.setToolTip(_translate("LexSearchForm", "search by dialects"))
        self.lDialectSearch.setToolTip(_translate("LexSearchForm", "search for dialectal forms"))
        self.lGrmDialectSearch.setToolTip(_translate("LexSearchForm", "search for dialect-specific \n"
                                                                      "grammatical forms"))
        self.lC2DialectSearch.setToolTip(_translate("LexSearchForm", "search for dialect-specific \n"
                                                                     "alternative forms"))
        self.lMetadataBox.setTitle(_translate("LexSearchForm", "Metadata"))
        self.lLabelSource.setText(_translate("LexSearchForm", "Source"))
        self.lLabelDate.setText(_translate("LexSearchForm", "Date"))
        self.lLabelResearcher.setText(_translate("LexSearchForm", "Researcher"))
        self.lLabelConfirmed.setText(_translate("LexSearchForm", "Confirmed"))
        self.lLabelUpdated.setText(_translate("LexSearchForm", "Updated"))
        self.lSearchSource.setToolTip(_translate("LexSearchForm", "search sources"))
        self.lSearchResearcher.setToolTip(_translate("LexSearchForm", "search researchers"))
        self.lSearchDate.setToolTip(_translate("LexSearchForm", "search by date of entry"))
        self.lSearchUpdate.setToolTip(_translate("LexSearchForm", "serach by date of updates"))
        self.lSearchConfirmed.setToolTip(_translate("LexSearchForm", "search for confirmations by consultant"))
        self.lDefBox.setTitle(_translate("LexSearchForm", "Definitions"))
        self.lL1Box.setTitle(_translate("LexSearchForm", "Primary language"))
        self.lL1Search.setToolTip(_translate("LexSearchForm", "search primary language gloss"))
        self.lL2Box.setTitle(_translate("LexSearchForm", "Secondary language"))
        self.lL2Search.setToolTip(_translate("LexSearchForm", "search secondary language gloss"))
        self.lIndexBox.setTitle(_translate("LexSearchForm", "Indices"))
        self.lKeywordsBox.setTitle(_translate("LexSearchForm", "Keywords"))
        self.lSearchKeywordIndex.setToolTip(_translate("LexSearchForm", "search keywords"))
        self.lPrimaryIndexBox.setTitle(_translate("LexSearchForm", "Primary"))
        self.lSearchPrimaryIndex.setToolTip(_translate("LexSearchForm", "search primary language index"))
        self.lSecondaryIndexBox.setTitle(_translate("LexSearchForm", "Secondary"))
        self.lSearchSecondaryIndex.setToolTip(_translate("LexSearchForm", "search secondary language index"))
        self.instructionBox.setTitle(_translate("LexSearchForm", "Instructions"))
        self.sDoneBtn.setToolTip(_translate("LexSearchForm", "Check box to search only completed entries.\n"
                                                             "Clear box to search for unfinished entries."))
        self.sDoneBtn.setText(_translate("LexSearchForm", "Done?"))
        self.doSearch.setToolTip(_translate("LexSearchForm", "Perform search"))
        self.doSearch.setText(_translate("LexSearchForm", "Submit"))
        self.lCancelSearch.setToolTip(_translate("LexSearchForm", "Cancel and go back to lexicon"))
        self.lCancelSearch.setText(_translate("LexSearchForm", "Cancel"))
        self.clearForm.setToolTip(_translate("LexSearchForm", "Clear all fields"))
        self.clearForm.setText(_translate("LexSearchForm", "Clear form"))
        self.searchParam.setTitle(_translate("LexSearchForm", "Settings"))
        self.caseBtn.setToolTip(_translate("LexSearchForm", "Perform case-insensitive searches."))
        self.caseBtn.setText(_translate("LexSearchForm", " Ignore case"))
        self.accentBtn.setToolTip(_translate("LexSearchForm", "Perform searches that ignore lexical accent.\n"
                                                              "Search term must contain no accented characters."))
        self.accentBtn.setText(_translate("LexSearchForm", " Ignore accents"))
        self.diacritBtn.setText(_translate("LexSearchForm", " Ignore diacrits"))
        self.appendBtn.setToolTip(_translate("LexSearchForm", "Search results will not overwrite the results\n"
                                                              "of previous searches on \"Search\" card."))
        self.appendBtn.setText(_translate("LexSearchForm", " Append results"))
        self.wholeWordBtn.setToolTip(_translate("LexSearchForm", "Find whole words only."))
        self.wholeWordBtn.setText(_translate("LexSearchForm", " Whole word"))
        self.setLangBtn.setToolTip(_translate("LexSearchForm", "Return results in secondary language."))
        self.setLangBtn.setText(_translate("LexSearchForm", " Secondary lang."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LexSearchForm = QtWidgets.QWidget()
    ui = Ui_LexSearchForm()
    ui.setupUi(LexSearchForm)
    LexSearchForm.show()
    sys.exit(app.exec())
