# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/David/Library/Mobile Documents/com~apple~CloudDocs/Current/ELFB/eFieldBook_Qt5/ELFB/palettes/LineSplitter.ui'
#
# Created by: PyQt6 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 440)
        Dialog.setSizeGripEnabled(False)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 9, 1080, 380))
        self.groupBox.setMinimumSize(QtCore.QSize(1080, 380))
        self.groupBox.setMaximumSize(QtCore.QSize(1080, 380))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.firstLine = QtWidgets.QTextEdit(self.groupBox)
        self.firstLine.setGeometry(QtCore.QRect(153, 15, 900, 30))
        self.firstLine.setMinimumSize(QtCore.QSize(900, 30))
        self.firstLine.setMaximumSize(QtCore.QSize(900, 30))
        self.firstLine.setObjectName("firstLine")
        self.secondLine = QtWidgets.QTextEdit(self.groupBox)
        self.secondLine.setGeometry(QtCore.QRect(153, 55, 900, 30))
        self.secondLine.setMinimumSize(QtCore.QSize(900, 30))
        self.secondLine.setMaximumSize(QtCore.QSize(900, 30))
        self.secondLine.setObjectName("secondLine")
        self.firstL1 = QtWidgets.QTextEdit(self.groupBox)
        self.firstL1.setGeometry(QtCore.QRect(153, 214, 900, 30))
        self.firstL1.setMinimumSize(QtCore.QSize(900, 30))
        self.firstL1.setMaximumSize(QtCore.QSize(900, 30))
        self.firstL1.setObjectName("firstL1")
        self.secondL1 = QtWidgets.QTextEdit(self.groupBox)
        self.secondL1.setGeometry(QtCore.QRect(153, 254, 900, 30))
        self.secondL1.setMinimumSize(QtCore.QSize(900, 30))
        self.secondL1.setMaximumSize(QtCore.QSize(900, 30))
        self.secondL1.setObjectName("secondL1")
        self.firstL2 = QtWidgets.QTextEdit(self.groupBox)
        self.firstL2.setGeometry(QtCore.QRect(153, 294, 900, 30))
        self.firstL2.setMinimumSize(QtCore.QSize(900, 30))
        self.firstL2.setMaximumSize(QtCore.QSize(900, 30))
        self.firstL2.setObjectName("firstL2")
        self.secondL2 = QtWidgets.QTextEdit(self.groupBox)
        self.secondL2.setGeometry(QtCore.QRect(153, 334, 900, 30))
        self.secondL2.setMinimumSize(QtCore.QSize(900, 30))
        self.secondL2.setMaximumSize(QtCore.QSize(900, 30))
        self.secondL2.setObjectName("secondL2")
        self.egArea = QtWidgets.QScrollArea(self.groupBox)
        self.egArea.setGeometry(QtCore.QRect(153, 95, 900, 95))
        self.egArea.setMinimumSize(QtCore.QSize(900, 95))
        self.egArea.setMaximumSize(QtCore.QSize(900, 95))
        self.egArea.setWidgetResizable(True)
        self.egArea.setObjectName("egArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 898, 93))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.egArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(371, 193, 500, 16))
        self.label.setMinimumSize(QtCore.QSize(500, 16))
        self.label.setMaximumSize(QtCore.QSize(500, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(35, 22, 110, 16))
        self.label_2.setMinimumSize(QtCore.QSize(110, 16))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(35, 62, 110, 16))
        self.label_3.setMinimumSize(QtCore.QSize(110, 16))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(35, 221, 110, 16))
        self.label_4.setMinimumSize(QtCore.QSize(110, 16))
        self.label_4.setMaximumSize(QtCore.QSize(110, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(35, 301, 110, 16))
        self.label_5.setMinimumSize(QtCore.QSize(110, 16))
        self.label_5.setMaximumSize(QtCore.QSize(110, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(35, 261, 110, 16))
        self.label_6.setMinimumSize(QtCore.QSize(110, 16))
        self.label_6.setMaximumSize(QtCore.QSize(110, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(35, 341, 110, 16))
        self.label_7.setMinimumSize(QtCore.QSize(110, 16))
        self.label_7.setMaximumSize(QtCore.QSize(110, 16))
        self.label_7.setObjectName("label_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(901, 398, 164, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Line splitter"))
        self.label.setText(_translate("Dialog", "Select the column where the new example begins by clicking on its number."))
        self.label_2.setText(_translate("Dialog", "First half (line)"))
        self.label_3.setText(_translate("Dialog", "Second half (line)"))
        self.label_4.setText(_translate("Dialog", "First half (L1)"))
        self.label_5.setText(_translate("Dialog", "First half (L2)"))
        self.label_6.setText(_translate("Dialog", "Second half (L1)"))
        self.label_7.setText(_translate("Dialog", "Second half (L2)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())

