# Form implementation generated from reading ui file '/Users/David/OpenSource/github/ELFB/eFieldBook_Qt5/ELFB/palettes/SearchHelp.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SearchHelpDialog(object):
    def setupUi(self, SearchHelpDialog):
        SearchHelpDialog.setObjectName("SearchHelpDialog")
        SearchHelpDialog.resize(507, 576)
        SearchHelpDialog.setSizeGripEnabled(True)
        self.helpText = QtWidgets.QTextEdit(SearchHelpDialog)
        self.helpText.setGeometry(QtCore.QRect(14, 12, 481, 509))
        self.helpText.setObjectName("helpText")
        self.buttonBox = QtWidgets.QDialogButtonBox(SearchHelpDialog)
        self.buttonBox.setGeometry(QtCore.QRect(321, 534, 164, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(SearchHelpDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchHelpDialog)

    def retranslateUi(self, SearchHelpDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchHelpDialog.setWindowTitle(_translate("SearchHelpDialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchHelpDialog = QtWidgets.QDialog()
    ui = Ui_SearchHelpDialog()
    ui.setupUi(SearchHelpDialog)
    SearchHelpDialog.show()
    sys.exit(app.exec())
