# Form implementation generated from reading ui file 'ELFB/palettes/SelectOutputSchema.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectOutput(object):
    def setupUi(self, SelectOutput):
        SelectOutput.setObjectName("SelectOutput")
        SelectOutput.resize(230, 298)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SelectOutput)
        self.buttonBox.setGeometry(QtCore.QRect(27, 250, 193, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.schemaList = QtWidgets.QListWidget(parent=SelectOutput)
        self.schemaList.setGeometry(QtCore.QRect(20, 41, 190, 198))
        self.schemaList.setObjectName("schemaList")
        self.label = QtWidgets.QLabel(parent=SelectOutput)
        self.label.setGeometry(QtCore.QRect(42, 13, 143, 16))
        self.label.setObjectName("label")

        self.retranslateUi(SelectOutput)
        self.buttonBox.accepted.connect(SelectOutput.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectOutput.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectOutput)

    def retranslateUi(self, SelectOutput):
        _translate = QtCore.QCoreApplication.translate
        SelectOutput.setWindowTitle(_translate("SelectOutput", "Output formats"))
        self.label.setText(_translate("SelectOutput", "Select an output format"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectOutput = QtWidgets.QDialog()
    ui = Ui_SelectOutput()
    ui.setupUi(SelectOutput)
    SelectOutput.show()
    sys.exit(app.exec())
