# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/David/Library/Mobile Documents/com~apple~CloudDocs/Current/ELFB/eFieldBook_Qt5/ELFB/palettes/TextSearchDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchTexts(object):
    def setupUi(self, SearchTexts):
        SearchTexts.setObjectName("SearchTexts")
        SearchTexts.resize(519, 353)
        self.buttonBox = QtWidgets.QDialogButtonBox(SearchTexts)
        self.buttonBox.setGeometry(QtCore.QRect(420, 282, 81, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(SearchTexts)
        self.groupBox.setGeometry(QtCore.QRect(349, 0, 148, 107))
        self.groupBox.setObjectName("groupBox")
        self.Source = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Source.setGeometry(QtCore.QRect(8, 39, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Source.setFont(font)
        self.Source.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Source.setObjectName("Source")
        self.Researcher = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Researcher.setGeometry(QtCore.QRect(80, 39, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Researcher.setFont(font)
        self.Researcher.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Researcher.setObjectName("Researcher")
        self.Date = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Date.setGeometry(QtCore.QRect(8, 78, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Date.setFont(font)
        self.Date.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Date.setObjectName("Date")
        self.Updated = QtWidgets.QPlainTextEdit(self.groupBox)
        self.Updated.setGeometry(QtCore.QRect(80, 78, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Updated.setFont(font)
        self.Updated.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Updated.setObjectName("Updated")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(8, 22, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 22, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(8, 61, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(80, 61, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(SearchTexts)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 270, 150, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Comments = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.Comments.setGeometry(QtCore.QRect(8, 22, 134, 42))
        self.Comments.setObjectName("Comments")
        self.groupBox_3 = QtWidgets.QGroupBox(SearchTexts)
        self.groupBox_3.setGeometry(QtCore.QRect(182, 270, 150, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Keywords = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.Keywords.setGeometry(QtCore.QRect(8, 22, 134, 42))
        self.Keywords.setObjectName("Keywords")
        self.groupBox_4 = QtWidgets.QGroupBox(SearchTexts)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 312, 241))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1, 0, 311, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(8, 0, 8, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.Line = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.Line.setMinimumSize(QtCore.QSize(295, 25))
        self.Line.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Line.setFont(font)
        self.Line.setObjectName("Line")
        self.verticalLayout.addWidget(self.Line)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.Morph = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.Morph.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Morph.setFont(font)
        self.Morph.setObjectName("Morph")
        self.verticalLayout.addWidget(self.Morph)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.ILEG = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.ILEG.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ILEG.setFont(font)
        self.ILEG.setObjectName("ILEG")
        self.verticalLayout.addWidget(self.ILEG)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.L1Gloss = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.L1Gloss.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.L1Gloss.setFont(font)
        self.L1Gloss.setObjectName("L1Gloss")
        self.verticalLayout.addWidget(self.L1Gloss)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.L2Gloss = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.L2Gloss.setMaximumSize(QtCore.QSize(295, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.L2Gloss.setFont(font)
        self.L2Gloss.setObjectName("L2Gloss")
        self.verticalLayout.addWidget(self.L2Gloss)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(SearchTexts)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(371, 121, 111, 158))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.caseBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.caseBtn.setFont(font)
        self.caseBtn.setChecked(True)
        self.caseBtn.setObjectName("caseBtn")
        self.verticalLayout_2.addWidget(self.caseBtn)
        self.accentBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.accentBtn.setFont(font)
        self.accentBtn.setObjectName("accentBtn")
        self.verticalLayout_2.addWidget(self.accentBtn)
        self.diacritBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.diacritBtn.setFont(font)
        self.diacritBtn.setObjectName("diacritBtn")
        self.verticalLayout_2.addWidget(self.diacritBtn)
        self.wholeWordBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.wholeWordBtn.setFont(font)
        self.wholeWordBtn.setObjectName("wholeWordBtn")
        self.verticalLayout_2.addWidget(self.wholeWordBtn)
        self.appendBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.appendBtn.setFont(font)
        self.appendBtn.setObjectName("appendBtn")
        self.verticalLayout_2.addWidget(self.appendBtn)
        self.setLangBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.setLangBtn.setFont(font)
        self.setLangBtn.setObjectName("setLangBtn")
        self.verticalLayout_2.addWidget(self.setLangBtn)
        self.limitBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.limitBtn.setFont(font)
        self.limitBtn.setChecked(True)
        self.limitBtn.setObjectName("limitBtn")
        self.verticalLayout_2.addWidget(self.limitBtn)
        self.textSearchHelpBtn = QtWidgets.QToolButton(SearchTexts)
        self.textSearchHelpBtn.setGeometry(QtCore.QRect(361, 290, 36, 36))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.textSearchHelpBtn.setFont(font)
        self.textSearchHelpBtn.setObjectName("textSearchHelpBtn")

        self.retranslateUi(SearchTexts)
        self.buttonBox.accepted.connect(SearchTexts.accept)
        self.buttonBox.rejected.connect(SearchTexts.reject)
        QtCore.QMetaObject.connectSlotsByName(SearchTexts)
        SearchTexts.setTabOrder(self.Line, self.Morph)
        SearchTexts.setTabOrder(self.Morph, self.ILEG)
        SearchTexts.setTabOrder(self.ILEG, self.L1Gloss)
        SearchTexts.setTabOrder(self.L1Gloss, self.L2Gloss)
        SearchTexts.setTabOrder(self.L2Gloss, self.Comments)
        SearchTexts.setTabOrder(self.Comments, self.Keywords)
        SearchTexts.setTabOrder(self.Keywords, self.Source)
        SearchTexts.setTabOrder(self.Source, self.Researcher)
        SearchTexts.setTabOrder(self.Researcher, self.Date)
        SearchTexts.setTabOrder(self.Date, self.Updated)
        SearchTexts.setTabOrder(self.Updated, self.limitBtn)
        SearchTexts.setTabOrder(self.limitBtn, self.caseBtn)
        SearchTexts.setTabOrder(self.caseBtn, self.buttonBox)
        SearchTexts.setTabOrder(self.buttonBox, self.accentBtn)
        SearchTexts.setTabOrder(self.accentBtn, self.diacritBtn)
        SearchTexts.setTabOrder(self.diacritBtn, self.appendBtn)

    def retranslateUi(self, SearchTexts):
        _translate = QtCore.QCoreApplication.translate
        SearchTexts.setWindowTitle(_translate("SearchTexts", "Dialog"))
        SearchTexts.setToolTip(_translate("SearchTexts", "select search help (?) below for instructions"))
        self.groupBox.setTitle(_translate("SearchTexts", "Metadata"))
        self.label.setText(_translate("SearchTexts", "Source"))
        self.label_2.setText(_translate("SearchTexts", "Researcher"))
        self.label_3.setText(_translate("SearchTexts", "Date"))
        self.label_4.setText(_translate("SearchTexts", "Updated"))
        self.groupBox_2.setTitle(_translate("SearchTexts", "Comments"))
        self.groupBox_3.setTitle(_translate("SearchTexts", "Keywords"))
        self.label_5.setText(_translate("SearchTexts", "Line"))
        self.label_6.setText(_translate("SearchTexts", "Morph"))
        self.label_7.setText(_translate("SearchTexts", "ILEG"))
        self.label_8.setText(_translate("SearchTexts", "Primary language gloss"))
        self.label_9.setText(_translate("SearchTexts", "Secondary language gloss"))
        self.caseBtn.setToolTip(_translate("SearchTexts", "Perform case-insensitive searches"))
        self.caseBtn.setText(_translate("SearchTexts", "Ignore case"))
        self.accentBtn.setToolTip(_translate("SearchTexts", "Perform searches that ignore lexical accent.\n"
"Search term must contain no accented characters."))
        self.accentBtn.setText(_translate("SearchTexts", "Ignore accents"))
        self.diacritBtn.setToolTip(_translate("SearchTexts", "Perform searches that ignore diacritics. \n"
"Search term must contain no diacritics."))
        self.diacritBtn.setText(_translate("SearchTexts", "Ignore diacrits"))
        self.wholeWordBtn.setText(_translate("SearchTexts", "Whole word"))
        self.appendBtn.setToolTip(_translate("SearchTexts", "Search results will not overwrite the results\n"
"of previous searches on \"Search\" card."))
        self.appendBtn.setText(_translate("SearchTexts", "Append results"))
        self.setLangBtn.setText(_translate("SearchTexts", "Second language"))
        self.limitBtn.setText(_translate("SearchTexts", "this text only"))
        self.textSearchHelpBtn.setToolTip(_translate("SearchTexts", "search help"))
        self.textSearchHelpBtn.setText(_translate("SearchTexts", "?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchTexts = QtWidgets.QDialog()
    ui = Ui_SearchTexts()
    ui.setupUi(SearchTexts)
    SearchTexts.show()
    sys.exit(app.exec_())

